### ISSUE TITLE
Running exporter into local OSS Grafana (Ubuntu)

### ISSUE THREAD

**Issue by DavidAuger** [guicaulada/vscode-exporter#6]
Hello @guicaulada,

I tried to avoid using Grafana Cloud and replaced it by an service OSS running on Ubuntu (WSL 2).
Get some issues to manage Grafana Agent and Prometheus, maily due to my lacks of understanding flows beetween those 2.

I use a Prometheus docker image and Grafana Agent service.

Have you any idea on how to proceed ? I bet it is about Agent's configuration but don't manage to find how to solve it.

Thank you in advance for your help !
Best regards,
David

**Comment by guicaulada** [comment]
In this case, Grafana Agent is being used to facilitate pushing metrics to Prometheus on Grafana Cloud.

Locally, for a simpler setup, I'd probably just use Prometheus directly and configure it to scrape my VSCode Exporter endpoint, I would then add that Prometheus as a Data Source on my local Grafana instance.

If you have any questions about how to configure Prometheus to scrape VSCode Exporter, I could help with that as well, but it follow the standard approach to scrape any endpoint using Prometheus.

For example:
```
    static_configs:
      - targets: ['localhost: 9931']
        labels:
          job: 'vscode'
 ```
 
 For more information about scrape configuration on Prometheus you can check their [documentation](https://prometheus.io/docs/prometheus/latest/getting_started/).
 
 I hope this helps!
 I'm available for any other questions. :)

**Comment by guicaulada** [comment]
Hi David,

Please let me know if this has solved your problem.

**Comment by DavidAuger** [comment]
Hello Guilherme,

Thank you for all those informations.
I am just back from a week off. Sorry for not responding.

I will try to take some time this week to change configuration according to your indications and contact you back as soon as possible with RETEX or question :)


Thank you again and best regards,
David

**Comment by DavidAuger** [comment]
Hello Guilherme,

I made some experimentations and may have some RETEX to share. Hope it could help and be interesting.

**You are right and Grafana Agent is not required in architect such mine (local Grafana OSS environment)**

Long story short:
- Intalled and using VsCode on Windows
- Using WSL2 to be hosted under Ubuntu
  - Grafana OSS service installed and accessed locally (http://localhost:3000)
  - Prometheus installed and accessed locally (http://localhost:9090/metrics)
    - just followed official documentation: https://prometheus.io/docs/introduction/first_steps/
    - modified prometheus.yaml adding new job:
      ``` yaml
      - job_name: "vscode"
        static_configs:
          - targets: ["172.XX.XXX.X:9931"]
      ```

    - run prometheus loading config file using command

Let's explain usage of ip istead of localhost: Main issue here is - from my understanding - Windows can access WSL2's ports using 'localhost' but reverse is ... more painful should we say. So in my case, Prometheus, on WSL2, was unable to see vscode-exporter and its port as it was running on Windows - even if lunch from Ubuntu through ```code .```.
Found some explainations here: https://github.com/microsoft/WSL/issues/5211#issuecomment-1192922575 (all thread and espacially link response)

After configuring Prometheus using IPV4 address from ```Ethernet adapter vEthernet (WSL)```, was able to seen data in my dashboard.

(1/2)

**Comment by DavidAuger** [comment]
(2/2)

However, i may have some other observations i wish to discuss with you.
I am not understanding everything well so, please consider all of this points as kindly discussion and observations. Absolutely no critisms at all, here.

- Noticed strange behavior requesting http://localhost:9931/metrics
  I am sometimes able to request all metrics and their documentation calling url http://localhost:9931/metrics in web browser or Postman for instance on Windows. But also observed that many times i reached a connection failure. Even using curl on WSL is failing.
  Have you any idea why is it sometimes responding and sometimes not ?

- Cannot see metrics joined to Prometheus' metrics, even if it is possible to see some metrics added after adding a job 'vscode'.
  Is it a normal behavior ? Shouldn't we see vscode-exporter's metrics requesting metrics from Prometheus ?

Thank you in advance for your time and response.
Best regards,
David

**Comment by guicaulada** [comment]
Hello David!

Thank you for sharing, I'm glad you figured it out and got it to work on Windows using WSL.

Regarding the first issue with connection failures, the exporter is only available while the VSCode Window is focused, the http webserver is shutdown when the window is unfocused, this is to allow metrics to be collected from multiple windows of vscode using the same port.

You can see the metrics within vscode using the CTRL+SHIFT+P and choosing the Open metrics command.

If your metrics are being scrapped properly from the endpoint you should be able to see the metrics exported by vscode exporter such as `vscode_editor_seconds_active` for example.
